version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sabri
      POSTGRES_PASSWORD: amazingpassword
      POSTGRES_DB: forumDatabase
    ports:
      - "5432:5432"
    volumes:
      - forumData:/var/lib/postgresql/data  
volumes:
  forumData: {}